
# ?? ??? ?? ??
server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  # DB ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db-exercise
    username: root
    password: root1234

  # JPA ??
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create

jwt:
  token:
    secret: aldskfjlaksdjf